-- =============================================================================
-- MMCD Dashboard - Dynamic Routing Initialization
-- =============================================================================
-- Runs once when OpenResty master process starts (init_by_lua_file).
-- Reads the worker list from a file generated by startup.sh and stores it
-- in a shared dict so access_by_lua can use it without file I/O.
-- =============================================================================

local config = ngx.shared.config

-- Read worker list from file (generated by startup.sh)
local workers_file = "/etc/nginx/workers.list"
local f = io.open(workers_file, "r")
if f then
    local content = f:read("*all")
    f:close()
    -- Trim trailing whitespace
    content = content:gsub("%s+$", "")
    config:set("workers", content)

    -- Count workers
    local count = 0
    for _ in content:gmatch("[^\n]+") do
        count = count + 1
    end
    config:set("worker_count", count)

    ngx.log(ngx.NOTICE, "[route-init] Loaded ", count, " workers from ", workers_file)
else
    ngx.log(ngx.WARN, "[route-init] Workers file not found: ", workers_file,
            " — dynamic routing will use fallback hash")
end

-- Store route TTL (can be overridden via env var ROUTE_TTL_SECONDS)
local ttl = os.getenv("ROUTE_TTL_SECONDS") or "600"
config:set("route_ttl", tonumber(ttl))
ngx.log(ngx.NOTICE, "[route-init] Route TTL: ", ttl, "s")

-- Queue configuration (overridable via env vars)
local queue_retries = os.getenv("QUEUE_MAX_RETRIES") or "5"
config:set("queue_max_retries", tonumber(queue_retries))
local queue_delay = os.getenv("QUEUE_RETRY_DELAY") or "2"
config:set("queue_retry_delay", tonumber(queue_delay))
ngx.log(ngx.NOTICE, "[route-init] Queue: max_retries=", queue_retries,
        " delay=", queue_delay, "s (max wait ",
        tonumber(queue_retries) * tonumber(queue_delay), "s)")
